import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";

const MatchPage: NextPage = () => {
  const { id } = useRouter().query;
  return (
    <>
      <Head>
        <title>Matches | League1 Ontario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>match page for {id}</p>
    </>
  );
};

export default MatchPage;
