import type { NextPage } from "next";
import { api } from "~/utils/api";
import Head from "next/head";

const MatchList: NextPage = () => {
  const { data, isLoading } = api.matches.getUserMatches.useQuery();

  if (isLoading) return <p>LOADING</p>;
  if (!data) return <p>something went wrong</p>;

  return (
    <>
      <Head>
        <title>Matches | League1 Ontario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>MATCHES LOADED</p>
      <p>{data[0]?.homeTeam.name}</p>
    </>
  );
};

export default MatchList;
