import type { NextPage } from "next";
import { api } from "~/utils/api";
import Head from "next/head";
import MatchListItem from "~/components/MatchListItem";

const MatchList: NextPage = () => {
  const ctx = api.useContext();
  const { data, isLoading } = api.matches.getUserMatches.useQuery();

  const { mutate: deleteMatch, isLoading: isDeletingMatch } =
    api.matches.deleteCreatedMatch.useMutation({
      onSuccess: () => {
        void ctx.matches.getUserMatches.invalidate();
      },
    });

  const deleteCreatedMatch = (id: number) => {
    deleteMatch({ id });
  };

  if (isLoading) return <p>LOADING</p>;
  if (!data) return <p>something went wrong</p>;

  return (
    <>
      <Head>
        <title>Matches | League1 Ontario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto my-10">
        <div className="grid grid-cols-1 gap-x-40 gap-y-10 p-1 lg:grid-cols-2 xl:grid-cols-3">
          {data.map((match) => (
            <MatchListItem
              key={match.id}
              homeTeam={match.homeTeam}
              awayTeam={match.awayTeam}
              scheduledTime={match.scheduledTime}
              division={match.division.name}
              id={match.id}
              onDeleteMatch={deleteCreatedMatch}
            />
          ))}
        </div>
      </div>
      <div />
    </>
  );
};

export default MatchList;
