import type { NextPage } from "next";
import { api } from "~/utils/api";
import { useState, useEffect } from "react";
import Loading from "~/components/Loading";
import Head from "next/head";
import useToast from "~/hooks/useToast";
import Toast from "~/components/Toast";

type Team = {
  id: number;
  name: string;
};

type NewMatchInput = {
  division: number;
  homeTeamId: number;
  awayTeamId: number;
  e2eNumber: number;
  scheduledTime: string;
};

const CreateMatchPage: NextPage = () => {
  const { data, isLoading } = api.divisions.getFormDivisionAndTeams.useQuery();

  const { toastStatus, toastMessage, dispatchToast } = useToast();

  const { mutate, isLoading: isCreatingMatch } =
    api.matches.createOrUpdateNewMatch.useMutation({
      onSuccess: () => {
        displaySuccessToast();
        resetForm();
      },
    });

  const createNewMatch = ({
    division,
    homeTeamId,
    awayTeamId,
    e2eNumber,
    scheduledTime,
  }: NewMatchInput) => {
    mutate({ division, homeTeamId, awayTeamId, e2eNumber, scheduledTime });
  };

  const displaySuccessToast = () => {
    dispatchToast({ type: "SET_SUCCESS", message: "Match created!" });
  };

  const [division, setDivision] = useState(0);
  const [teamsList, setTeamsList] = useState<Team[] | undefined>([]);
  const [homeTeamId, setHomeTeamId] = useState(0);
  const [awayTeamId, setAwayTeamId] = useState(0);
  const [e2eNumber, setE2eNumber] = useState("");
  const [scheduledTime, setScheduledTime] = useState("");

  const resetForm = () => {
    setDivision(0);
    setTeamsList([]);
    setHomeTeamId(0);
    setAwayTeamId(0);
    setE2eNumber("");
    setScheduledTime("");
  };

  const resetToast = () => {
    dispatchToast({ type: "CLEAR_TOAST", message: "" });
  };

  useEffect(() => {
    if (isCreatingMatch) {
      dispatchToast({ type: "SET_WARNING", message: "Creating your match..." });
    }
  }, [isCreatingMatch, dispatchToast]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center">
        <Loading />
      </div>
    );
  }

  if (!data) return <p>SOMETHING WENT WRONG</p>;

  return (
    <>
      <Head>
        <title>Create a new match | League1 Ontario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className="flex flex-col items-center justify-center gap-6 px-4">
        <select
          className="select-bordered select w-full max-w-xs"
          onChange={(event) => {
            const divId = parseInt(event.target.value, 10);
            setDivision(divId);
            setTeamsList(data.find((division) => division.id === divId)?.teams);
            setHomeTeamId(0);
            setAwayTeamId(0);
          }}
          value={division}
          onFocus={() => resetToast()}
        >
          <option disabled value={0}>
            Pick a division.
          </option>
          {data.map((division) => (
            <option value={division.id} key={division.id}>
              {division.name}
            </option>
          ))}
        </select>
        <select
          className="select-bordered select w-full max-w-xs"
          onChange={(event) => {
            setHomeTeamId(parseInt(event.target.value, 10));
            setAwayTeamId(0);
          }}
          disabled={division < 1}
          value={homeTeamId}
        >
          <option disabled value={0}>
            Pick a home team.
          </option>
          {teamsList?.map((team) => (
            <option value={team.id} key={team.id}>
              {team.name}
            </option>
          ))}
        </select>
        <select
          className="select-bordered select w-full max-w-xs"
          onChange={(event) => {
            setAwayTeamId(parseInt(event.target.value, 10));
          }}
          disabled={division < 1 || homeTeamId < 1}
          value={awayTeamId}
        >
          <option disabled value={0}>
            Pick an away team.
          </option>
          {teamsList
            ?.filter((team) => team.id !== homeTeamId)
            .map((team) => (
              <option value={team.id} key={team.id}>
                {team.name}
              </option>
            ))}
        </select>
        <input
          type="number"
          placeholder="Type E2E ID here"
          className="input-bordered input w-full max-w-xs"
          value={e2eNumber}
          onChange={(event) => setE2eNumber(event.target.value)}
          onFocus={() => resetToast()}
        />
        <input
          type="datetime-local"
          className="input-bordered input w-full max-w-xs"
          onChange={(event) => {
            const date = new Date(event.target.value);
            setScheduledTime(date.toISOString());
          }}
          onFocus={() => resetToast()}
        />
        <button
          disabled={
            division <= 0 ||
            homeTeamId <= 0 ||
            awayTeamId <= 0 ||
            !e2eNumber ||
            !scheduledTime
          }
          className="btn-primary btn"
          onClick={(event) => {
            event.preventDefault();
            createNewMatch({
              division,
              homeTeamId,
              awayTeamId,
              e2eNumber: parseInt(e2eNumber, 10),
              scheduledTime,
            });
          }}
        >
          Create match
        </button>
      </form>
      <Toast status={toastStatus} message={toastMessage} />
    </>
  );
};

export default CreateMatchPage;
