import type { NextPage } from "next";
import Head from "next/head";
import Login from "~/components/Login";
import { SignedIn, SignedOut } from "@clerk/nextjs";
import Welcome from "~/components/Welcome";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MDOC Assistant | League1 Ontario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignedOut>
        <Login />
      </SignedOut>
      <SignedIn>
        <Welcome />
      </SignedIn>
    </>
  );
};

export default Home;
