import { type NextPage } from "next";
import Head from "next/head";
import Login from "~/components/Login";
import { useUser, SignOutButton } from "@clerk/nextjs";
import MatchesList from "~/components/MatchesList";

const Home: NextPage = () => {
  const { user, isSignedIn, isLoaded } = useUser();

  return (
    <>
      <Head>
        <title>MDOC Assistant | League1 Ontario</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoaded && !isSignedIn && <Login />}
      {isLoaded && isSignedIn && (
        <>
          <p>{user.fullName}</p>
          <SignOutButton />
          <MatchesList userId={user.id} />
        </>
      )}
    </>
  );
};

export default Home;
